{
 "title": "Exam Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Apache-Kafka",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discoverer-Facts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "discovered_facts_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time-Spent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "time_spent_total", "legendFormat": "__auto" }
   ]
  }
 ]
}